<div class="container">

    <!-- Docs nav
    ================================================== -->
    <div class="row">
        <div class="span3 bs-docs-sidebar">
            <ul class="nav nav-list bs-docs-sidenav">
                <li><a href="#download-lucene"><i class="icon-chevron-right"></i> Pobieranie</a></li>
                <li><a href="#file-structure"><i class="icon-chevron-right"></i> File structure</a></li>
            </ul>
        </div>
        <div class="span9">



            <!-- Download
            ================================================== -->
            <section id="download-lucene">
                <div class="page-header">
                    <h1>1. Pobieranie</h1>
                </div>
                <p class="lead">Główna strona biblioteki <a href="http://lucene.apache.org/">http://lucene.apache.org/</a></p>

                <div class="row-fluid">
                    <div class="span6">
                        <h2>Wersja 3.6.2</h2>
                        <p><a class="btn btn-large btn-primary" href="http://ftp.ps.pl/pub/apache/lucene/java/3.6.2/lucene-3.6.2.zip" onclick="_gaq.push(['_trackEvent', 'About', 'Download', 'Version 3.6.2']);">Pobierz bibliotekę 3.6.2</a></p>
                    </div>
                    <div class="span6">
                        <h2>Wersja 4.3.0</h2>
                        <p><a class="btn btn-large" href="http://ftp.ps.pl/pub/apache/lucene/java/4.3.0/lucene-4.3.0.zip" onclick="_gaq.push(['_trackEvent', 'About', 'Download', 'Version 4.3.0']);">Pobierz bibliotekę 4.3.0</a></p>
                    </div>
                </div>
            </section>



            <!-- File structure
            ================================================== -->
            <section id="file-structure">
                <div class="page-header">
                    <h1>2. Opis</h1>
                </div>
                <p class="lead">Biblioteka języka JAVA umożliwiająca wyszukiwanie pełno tekstowe. Zaprojektowana została przez Doug'a Cutting'a i jest wspierana przez Apache Software Foundation.</p>
                <p>Biblioteka w ostatnich latach znacznie zyskała na popularności a także została przeniesiona na inne platformy jak Delphi, Perl, C#, C++, Python, Ruby, PHP. </p>
                <p>Głównym z czynników popularności Lucene jest łatwość w implementacji, wysoka wydajność i skalowalność, niewielki rozmiar rdzenia biblioteki który zajmuje około 1MB,
                    a przede wszystkim jej darmowa licencja. Lucene jest narzędziemy wyszukiwania informacji (information retrieval IR).
                </p>

                <p>Lucene umożliwia indeksowanie danych tekstowych różnego rodzaju, jak np. strony internetowe, proste pliki tekstowe, dokumenty Microsoft Office Word, pliki XML lub  HTML oraz dokumenty PDF.</p>
            </section>


        </div>
    </div>

</div>