<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Getting · Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/assets/css/bootstrap.css" rel="stylesheet">
    <link href="/assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/assets/css/docs.css" rel="stylesheet">
    <link href="/assets/js/google-code-prettify/prettify.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="/assets/js/html5shiv.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="/assets/ico/favicon.png">

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-41348202-1', 'lucene.pl');
        ga('send', 'pageview');

    </script>
</head>

<body data-spy="scroll" data-target=".bs-docs-sidebar">
<?php echo $this->layout()->content; ?>
<!-- Navbar
================================================== -->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="/">Lucene Search</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="">
                        <a href="/">Home</a>
                    </li>
                    <li class="active">
                        <a href="/info">O bibliotece</a>
                    </li>
                    <li class="">
                        <a href="/java">Java</a>
                    </li>
                    <li class="">
                        <a href="/php">PHP</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Footer
================================================== -->
<footer class="footer">
    <div class="container">
        <p>Autorzy <a href="http://www.linkedin.com/in/slawomirzytko" target="_blank">Sławomir Żytko</a> <a href="#" target="_blank">Łukasz Szumilas</a> <a href="#" target="_blank">Hanna Moczko.</p>
        <ul class="footer-links">
            <li><a href="http://wszib.edu.pl">Wszib Kraków</a></li>
            <li class="muted">&middot;</li>
            <li><a href="https://github.com/szytko/lucene">Github PHP</a></li>
            <li class="muted">&middot;</li>
            <li><a href="https://github.com/szytko/lucene-java">Github Java</a></li>
        </ul>
    </div>
</footer>



<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
<script src="/assets/js/jquery.js"></script>
<script src="/assets/js/bootstrap-transition.js"></script>
<script src="/assets/js/bootstrap-alert.js"></script>
<script src="/assets/js/bootstrap-modal.js"></script>
<script src="/assets/js/bootstrap-dropdown.js"></script>
<script src="/assets/js/bootstrap-scrollspy.js"></script>
<script src="/assets/js/bootstrap-tab.js"></script>
<script src="/assets/js/bootstrap-tooltip.js"></script>
<script src="/assets/js/bootstrap-popover.js"></script>
<script src="/assets/js/bootstrap-button.js"></script>
<script src="/assets/js/bootstrap-collapse.js"></script>
<script src="/assets/js/bootstrap-carousel.js"></script>
<script src="/assets/js/bootstrap-typeahead.js"></script>
<script src="/assets/js/bootstrap-affix.js"></script>

<script src="/assets/js/holder/holder.js"></script>
<script src="/assets/js/google-code-prettify/prettify.js"></script>

<script src="/assets/js/application.js"></script>


</body>
</html>
